### ISSUE TITLE
Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by EvertS3** [codeschool/NoteWrangler#11]
I cloned the repo and tried running npm install, but got the following errors in the output terminal: 

```
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/home/evert/AngularJS/workspace/NoteWrangler/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/evert/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-85-generic
gyp ERR! command "/home/evert/local/bin/node" "/home/evert/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/evert/AngularJS/workspace/NoteWrangler/node_modules/bcrypt
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

```
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/home/evert/local/bin/node" "/home/evert/local/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/evert/AngularJS/workspace/NoteWrangler/npm-debug.log
```

Can anyone assist? I don't seem to be getting a solution myself...

**Comment by renz45** [comment]
Hi Evert,
Try downgrading to node 5.X, the .nvmrc is using 5.5.0

**Comment by EvertS3** [comment]
Hi Renz, 

I will try that, thanks.

**Comment by kgrube5** [comment]
Or npm install --save bcryptjs and go to app/server/modules/encrypt.js and change bcrypt = require('bcrypt') to bcrypt = require('bcryptjs');

I also had to run npm uninstall sqlite3 and then run npm install --save sqlite3

**Comment by anudeepbommidi** [comment]
@kgrube5 Your solution works, thanks!

**Comment by dsoldera** [comment]
Thanks @kgrube5! Its works now.

We need to insert this solution on the README.md for other people.

**Comment by tkaye407** [comment]
Hi, This is still very much an issue, and it seems like the repo is pretty far behind as we are currently in Node version 8 and this only works with 5. How should I be fixing this because the solution above does not seem to work?
