### ISSUE TITLE
Gravatar error on JS console

### ISSUE THREAD

**Issue by dvdcastro** [codeschool/NoteWrangler#5]
Hello,

When I start the app, nothing appears, eventhough it looks like the database loaded. I'm getting an error on the browser's JS console:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module NoteWrangler due to:
Error: [$injector:unpr] Unknown provider: $gravatarProvider
http://errors.angularjs.org/1.2.21/$injector/unpr?p0=%24gravatarProvider
    at VALIDITY_STATE_PROPERTY (http://localhost:8000/js/vendor/angular.js:78:12)
    at http://localhost:8000/js/vendor/angular.js:3776:19
    at getService (http://localhost:8000/js/vendor/angular.js:3904:39)
    at Object.invoke (http://localhost:8000/js/vendor/angular.js:3931:13)
    at http://localhost:8000/js/vendor/angular.js:3859:37
    at forEach (http://localhost:8000/js/vendor/angular.js:325:18)
    at loadModules (http://localhost:8000/js/vendor/angular.js:3846:5)
    at createInjector (http://localhost:8000/js/vendor/angular.js:3786:11)
    at doBootstrap (http://localhost:8000/js/vendor/angular.js:1435:20)
    at bootstrap (http://localhost:8000/js/vendor/angular.js:1450:12)
http://errors.angularjs.org/1.2.21/$injector/modulerr?p0=NoteWrangler&p1=Er…ap%20(http%3A%2F%2Flocalhost%3A8000%2Fjs%2Fvendor%2Fangular.js%3A1450%3A12)angular.js:78 VALIDITY_STATE_PROPERTYangular.js:3880 (anonymous function)angular.js:325 forEachangular.js:3846 loadModulesangular.js:3786 createInjectorangular.js:1435 doBootstrapangular.js:1450 bootstrapangular.js:1363 angularInitangular.js:21878 (anonymous function)jquery.js:3073 jQuery.Callbacks.firejquery.js:3185 jQuery.Callbacks.self.fireWithjquery.js:3391 jQuery.extend.readyjquery.js:3407 completed
```

**Comment by dastiii** [comment]
Try adding Gravatar as a dependency in your app/js/app.js like so:

```
angular.module('NoteWrangler', ['ngRoute', 'ngResource', 'Gravatar'])
```

Edit: There is already a pull-request that fixes the error, just needs to be merged.

**Comment by renz45** [comment]
This should be fixed now. I apologize for taking so long to respond, my notifications for this repo got turned off for some reason :(.
