### ISSUE TITLE
npm install - too many errors

### ISSUE THREAD

**Issue by ricardogomesdf** [codeschool/NoteWrangler#8]
Hi all.

When I run "npm install" in NoteWrangler root folder, too many errors are shown. The first error is:

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function
      call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~

What should I do to solve this?

Thanks in advance.

My environment:
OS X 10.10.5
Xcode 6.4
npm 2.14.2

**Comment by ricardogomesdf** [comment]
Hi all.

I solved this problem uninstalling npm 2.14.2 (node-v4.0.0.pkg) and after installed npm 2.11.3 (node-v0.12.7.pkg). NoteWrangler app working!

Thanks very much.

**Comment by zirho** [comment]
Tried to use nvm to use npm v2.11.3 
https://nodejs.org/en/download/releases/
it seemed not solving anything. 

htdocs/note-angular ] sudo npm install
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated lodash@0.9.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.

> bcrypt@0.8.2 install /Applications/XAMPP/xamppfiles/htdocs/note-angular/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function call,
      expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/zirho6/.node-gyp/2.3.3/deps/v8/include/v8.h:4188:3: note: 'New' declared here
  static Local<Signature> New(
  ^
../src/bcrypt_node.cc:85:19: warning: 'Encode' is deprecated: Use Encode(isolate, ...)
      [-Wdeprecated-declarations]
        argv[1] = Encode(salt.c_str(), salt.size(), BINARY);
                  ^
/Users/zirho6/.node-gyp/2.3.3/src/node.h:299:45: note: 'Encode' has been explicitly marked deprecated
      here
                inline v8::Localv8::Value Encode(
                                            ^
/Users/zirho6/.node-gyp/2.3.3/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    **attribute**((deprecated(message))) declarator
                                         ^
../src/bcrypt_node.cc:139:20: warning: 'Encode' is deprecated: Use Encode(isolate, ...)
      [-Wdeprecated-declarations]
    NanReturnValue(Encode(salt, strlen(salt), BINARY));
                   ^
../node_modules/nan/nan.h:306:65: note: expanded from macro 'NanReturnValue'

# define NanReturnValue(value) return args.GetReturnValue().Set(value)

```
                                                            ^
```

/Users/zirho6/.node-gyp/2.3.3/src/node.h:299:45: note: 'Encode' has been explicitly marked deprecated
      here
                inline v8::Localv8::Value Encode(
                                            ^
/Users/zirho6/.node-gyp/2.3.3/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    **attribute**((deprecated(message))) declarator
                                         ^
../src/bcrypt_node.cc:172:23: warning: 'Encode' is deprecated: Use Encode(isolate, ...)
      [-Wdeprecated-declarations]
            argv[1] = Encode(output.c_str(), output.size(), BINARY);
                      ^
/Users/zirho6/.node-gyp/2.3.3/src/node.h:299:45: note: 'Encode' has been explicitly marked deprecated
      here
                inline v8::Localv8::Value Encode(
                                            ^
/Users/zirho6/.node-gyp/2.3.3/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    **attribute**((deprecated(message))) declarator
                                         ^
../src/bcrypt_node.cc:223:20: warning: 'Encode' is deprecated: Use Encode(isolate, ...)
      [-Wdeprecated-declarations]
    NanReturnValue(Encode(bcrypted, strlen(bcrypted), BINARY));
                   ^
../node_modules/nan/nan.h:306:65: note: expanded from macro 'NanReturnValue'

# define NanReturnValue(value) return args.GetReturnValue().Set(value)

```
                                                            ^
```

/Users/zirho6/.node-gyp/2.3.3/src/node.h:299:45: note: 'Encode' has been explicitly marked deprecated
      here
                inline v8::Localv8::Value Encode(
                                            ^
/Users/zirho6/.node-gyp/2.3.3/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    **attribute**((deprecated(message))) declarator
                                         ^
4 warnings and 1 error generated.
make: **\* [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/zirho6/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/zirho6/.nvm/versions/io.js/v2.3.3/bin/iojs" "/Users/zirho6/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/XAMPP/xamppfiles/htdocs/note-angular/node_modules/bcrypt
gyp ERR! node -v v2.3.3
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

> ws@0.4.32 install /Applications/XAMPP/xamppfiles/htdocs/note-angular/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm WARN prefer global node-inspector@0.7.4 should be installed with -g
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/zirho6/.nvm/versions/io.js/v2.3.3/bin/iojs" "/Users/zirho6/.nvm/versions/io.js/v2.3.3/bin/npm" "install"
npm ERR! node v2.3.3
npm ERR! npm  v2.11.3
npm ERR! code ENOTSUP

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your version of node/npm: sqlite3@3.0.5
npm ERR! notsup Required: {"node":">= 0.10.0 < 0.11.0 || >= 0.11.13 < 0.13.0 || >= 1.0.0 < 2.0.0"}
npm ERR! notsup Actual:   {"npm":"2.11.3","node":"2.3.3"}

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/XAMPP/xamppfiles/htdocs/note-angular/npm-debug.log

**Comment by gVien** [comment]
if you tried `npm install` with the latest version of node (v5.5.5) without success and attempted to roll back a version such as the one @ricardogomesdf suggested, I suggest deleting your NoteWrangler folder and clone a new one. I think the folders got corrupted with too many `npm install` in many different versions of node. I did that and it works for me.

**Comment by renz45** [comment]
This should be fixed now. I apologize for not chiming in on this earlier, I must have accidentally turned off notifications for this repo. :( The solution was just updating bcrypt and sqlite3 modules.
